apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: authz-jwt
spec:
  hosts:
  - "*"
  gateways:
  - authz-jwt-gateway
  http:
  - name: "httpbin"
    route:
    - destination:
        host: httpbin
        port:
          number: 8000